export const pageData = [
  {
    slug: 'home',
    title: 'Home',
    metaTitle: 'Jakob Smith | Creative and Conscientious Web Developer',
    metaDescription: 'A digital marketing developer based in Albuquerque, New Mexico',
    metaKeywords: 'web development, digital marketing, Albuquerque, New Mexico',
    data: {
      href: '/',
      dataContent: 'the page with the rainbow',
      theme: 'rainbow',
    },
  },
  {
    slug: 'website-designers',
    title: 'Web Designers',
    metaTitle: 'Jakob Smith | Web Designers',
    metaDescription: 'Web designers who love keyboard shortcuts',
    metaKeywords: 'web design, keyboard shortcuts',
    data: {
      href: '/website-designers',
      dataContent: 'for those keyboard shortcut lovers',
      theme: 'red',
    },
  },
  {
    slug: 'marketing',
    title: 'Marketing',
    metaTitle: 'Jakob Smith | Marketing',
    metaDescription: 'Marketing strategies for the digital age',
    metaKeywords: 'marketing, digital marketing, SEO',
    data: {
      href: '/marketing',
      dataContent: 'for those who love to sell',
      theme: 'yellow',
    },
  },
  {
    slug: 'public-good',
    title: 'Public Good',
    metaTitle: 'Jakob Smith | Public Good',
    metaDescription: 'Web development for the public good',
    metaKeywords: 'public good, web development, community service',
    data: {
      href: '/public-good',
      dataContent: 'for those who kindly break even and take turns',
      theme: 'blue',
    },
  },
  {
    slug: 'how-we-handle-clients',
    title: 'Clients',
    metaTitle: 'Jakob Smith | How We Handle Clients',
    metaDescription: 'Learn how we work with our clients to achieve their goals',
    metaKeywords: 'client relations, web development, project management',
    data: {
      href: '/how-we-handle-clients',
      dataContent: 'how we work with clients',
      theme: 'rainbow',
    },
  },
  {
    slug: 'pricing',
    title: 'Pricing',
    metaTitle: 'Jakob Smith | Pricing',
    metaDescription: 'How much does it cost?',
    metaKeywords: 'pricing, web development, cost',
    data: {
      href: '/pricing',
      dataContent: 'how much?',
      theme: 'rainbow',
    },
  },
  {
    slug: 'maintenance',
    title: 'Maintenance',
    metaTitle: 'Jakob Smith | Maintenance',
    metaDescription: 'Keep your website running smoothly',
    metaKeywords: 'maintenance, web development, support',
    data: {
      href: '/maintenance',
      dataContent: 'keep it running good',
      theme: 'rainbow',
    },
  },
  {
    slug: 'portfolio',
    title: 'Portfolio',
    metaTitle: 'Jakob Smith | Portfolio',
    metaDescription: 'Examples of my skillsets',
    metaKeywords: 'portfolio, web development, design',
    data: {
      href: '/portfolio',
      dataContent: 'examples of my skillsets',
      theme: 'rainbow',
    },
  },
  {
    slug: 'about',
    title: 'About',
    metaTitle: 'Jakob Smith | About',
    metaDescription: 'A little about me',
    metaKeywords: 'about, web developer, personal',
    data: {
      href: '/about',
      dataContent: 'a little about me',
      theme: 'rainbow',
    },
  },
  {
    slug: 'contact',
    title: 'Contact',
    metaTitle: 'Jakob Smith | Contact',
    metaDescription: 'Get a hold of my attention',
    metaKeywords: 'contact, web developer, personal',
    data: {
      href: '/contact',
      dataContent: 'get a hold of my attention',
      theme: 'rainbow',
    },
  },
];
