// services are referenced by slug from servicesData.js
// slugs: simple-seo, content-gen, ai-discovery, additions, rebuild,
//        foundations, hosting-updates, support, total-debug

export const portfolioData = [
  {
    id: "ccim-new-mexico",
    name: "CCIM New Mexico",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "simple-seo"],
    href: "https://ccimnm.com/",
  },
  {
    id: "irem-new-mexico",
    name: "IREM New Mexico",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "hosting-updates"],
    href: "https://iremnewmex.org/",
  },
  {
    id: "base5-retail",
    name: "Base 5 Retail",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "foundations"],
    href: "https://base5retail.com/",
  },
  {
    id: "north-star-dental",
    name: "North Star Dental",
    clientCategories: ["digital-marketing"],
    services: ["simple-seo", "foundations"],
    href: "https://northstardentalabq.com/",
  },
  {
    id: "ray-steel",
    name: "Ray Steel",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "hosting-updates"],
    href: "https://www.raysteel.com/",
  },
  {
    id: "carristo-creative",
    name: "Carristo Creative",
    clientCategories: ["web-designers"],
    services: ["rebuild", "simple-seo"],
    href: "https://carristo.com/",
  },
  {
    id: "nai-el-paso",
    name: "NAI El Paso",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "hosting-updates"],
    href: "https://naielpaso.com/",
  },
  {
    id: "wtba",
    name: "WTBA",
    clientCategories: ["public-good"],
    services: ["rebuild", "support"],
    href: "https://wtba.org/",
  },
  {
    id: "nai-first-valley",
    name: "NAI First Valley",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "hosting-updates"],
    href: "https://1stvalley.com/",
  },
  {
    id: "kraemer-fields",
    name: "Kraemer Fields",
    clientCategories: ["public-good"],
    services: ["foundations"],
    href: "https://kraemerfields.com/",
  },
  {
    id: "nai-sunvista",
    name: "NAI Sunvista",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "hosting-updates"],
    href: "https://sunvista.com/",
  },
  {
    id: "cpix",
    name: "CPIX",
    clientCategories: ["digital-marketing"],
    services: ["hosting-updates", "support"],
    href: "https://cpix.net/",
  },
  {
    id: "carw",
    name: "CARW",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "support"],
    href: "https://carw.com/",
  },
  {
    id: "lindsey-homes",
    name: "Lindsey Homes",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "simple-seo"],
    href: "https://lindseyhomes.com/",
  },
  {
    id: "carnm",
    name: "CAR New Mexico",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "hosting-updates"],
    href: "https://carnm.realtor/",
  },
  {
    id: "carwm",
    name: "CARWM",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "support"],
    href: "https://carwm.com/",
  },
  {
    id: "commgate",
    name: "Commgate",
    clientCategories: ["digital-marketing"],
    services: ["rebuild", "simple-seo"],
    href: "https://commgate.com/",
  },
  {
    id: "get-a-grip",
    name: "Get A Grip",
    clientCategories: ["digital-marketing"],
    services: ["hosting-updates", "support"],
    href: "https://getagrip.com/",
  },
  {
    id: "ski-new-mexico",
    name: "Ski New Mexico",
    clientCategories: ["public-good"],
    services: ["simple-seo", "hosting-updates"],
    href: "https://skinewmexico.com/",
  },
  {
    id: "visit-angel-fire",
    name: "Visit Angel Fire",
    clientCategories: ["public-good"],
    services: ["rebuild", "simple-seo"],
    href: "https://visitangelfirenm.com/",
  },
];

export const portfolioClientCategories = [
  {
    id: "web-designers",
    label: "Web Designers",
  },
  {
    id: "digital-marketing",
    label: "Digital Marketing",
  },
  {
    id: "public-good",
    label: "Public Good",
  },
];
